#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:dynamic,enum,type_hints
#

from __future__ import annotations
import typing
from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec
from uuid import UUID
from enum import IntEnum

import sys
import logging
from .ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
from thrift.protocol.TBase import TBase, TFrozenBase, TExceptionBase, TFrozenExceptionBase, TTransport
all_structs = []


class Iface(object):
    def trainOnExample(self, features: list[float], result: int) -> None:
        """
        One online-training update using sgd.

        Parameters:
         - features
         - result

        """
        pass

    def predictProba(self, features: list[float]) -> float:
        """
        Predict probability for class=1

        Parameters:
         - features

        """
        pass


class Client(Iface):
    def __init__(self, iprot, oprot=None):
        self._iprot = self._oprot = iprot
        if oprot is not None:
            self._oprot = oprot
        self._seqid = 0

    def trainOnExample(self, features: list[float], result: int) -> None:
        """
        One online-training update using sgd.

        Parameters:
         - features
         - result

        """
        self.send_trainOnExample(features, result)
        self.recv_trainOnExample()

    def send_trainOnExample(self, features: list[float], result: int):
        self._oprot.writeMessageBegin('trainOnExample', TMessageType.CALL, self._seqid)
        args = trainOnExample_args()
        args.features = features
        args.result = result
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_trainOnExample(self) -> None:
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = trainOnExample_result()
        result.read(iprot)
        iprot.readMessageEnd()
        return

    def predictProba(self, features: list[float]) -> float:
        """
        Predict probability for class=1

        Parameters:
         - features

        """
        self.send_predictProba(features)
        return self.recv_predictProba()

    def send_predictProba(self, features: list[float]):
        self._oprot.writeMessageBegin('predictProba', TMessageType.CALL, self._seqid)
        args = predictProba_args()
        args.features = features
        args.write(self._oprot)
        self._oprot.writeMessageEnd()
        self._oprot.trans.flush()

    def recv_predictProba(self) -> float:
        iprot = self._iprot
        (fname, mtype, rseqid) = iprot.readMessageBegin()
        if mtype == TMessageType.EXCEPTION:
            x = TApplicationException()
            x.read(iprot)
            iprot.readMessageEnd()
            raise x
        result = predictProba_result()
        result.read(iprot)
        iprot.readMessageEnd()
        if result.success is not None:
            return result.success
        raise TApplicationException(TApplicationException.MISSING_RESULT, "predictProba failed: unknown result")


class Processor(Iface, TProcessor):
    def __init__(self, handler):
        self._handler = handler
        self._processMap = {}
        self._processMap["trainOnExample"] = Processor.process_trainOnExample
        self._processMap["predictProba"] = Processor.process_predictProba
        self._on_message_begin = None

    def on_message_begin(self, func):
        self._on_message_begin = func

    def process(self, iprot, oprot):
        (name, type, seqid) = iprot.readMessageBegin()
        if self._on_message_begin:
            self._on_message_begin(name, type, seqid)
        if name not in self._processMap:
            iprot.skip(TType.STRUCT)
            iprot.readMessageEnd()
            x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
            oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
            x.write(oprot)
            oprot.writeMessageEnd()
            oprot.trans.flush()
            return
        else:
            self._processMap[name](self, seqid, iprot, oprot)
        return True

    def process_trainOnExample(self, seqid, iprot, oprot):
        args = trainOnExample_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = trainOnExample_result()
        try:
            self._handler.trainOnExample(args.features, args.result)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("trainOnExample", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

    def process_predictProba(self, seqid, iprot, oprot):
        args = predictProba_args()
        args.read(iprot)
        iprot.readMessageEnd()
        result = predictProba_result()
        try:
            result.success = self._handler.predictProba(args.features)
            msg_type = TMessageType.REPLY
        except TTransport.TTransportException:
            raise
        except TApplicationException as ex:
            logging.exception('TApplication exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = ex
        except Exception:
            logging.exception('Unexpected exception in handler')
            msg_type = TMessageType.EXCEPTION
            result = TApplicationException(TApplicationException.INTERNAL_ERROR, 'Internal error')
        oprot.writeMessageBegin("predictProba", msg_type, seqid)
        result.write(oprot)
        oprot.writeMessageEnd()
        oprot.trans.flush()

# HELPER FUNCTIONS AND STRUCTURES


class trainOnExample_args(TBase):
    """
    Attributes:
     - features
     - result

    """
    thrift_spec: typing.Any = None


    def __init__(self, features: typing.Optional[list[float]] = None, result: typing.Optional[int] = None,):
        self.features: typing.Optional[list[float]] = features
        self.result: typing.Optional[int] = result

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(trainOnExample_args)
trainOnExample_args.thrift_spec = (
    None,  # 0
    (1, TType.LIST, 'features', (TType.DOUBLE, None, False), None, ),  # 1
    (2, TType.I32, 'result', None, None, ),  # 2
)


class trainOnExample_result(TBase):
    thrift_spec: typing.Any = None


    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(trainOnExample_result)
trainOnExample_result.thrift_spec = (
)


class predictProba_args(TBase):
    """
    Attributes:
     - features

    """
    thrift_spec: typing.Any = None


    def __init__(self, features: typing.Optional[list[float]] = None,):
        self.features: typing.Optional[list[float]] = features

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(predictProba_args)
predictProba_args.thrift_spec = (
    None,  # 0
    (1, TType.LIST, 'features', (TType.DOUBLE, None, False), None, ),  # 1
)


class predictProba_result(TBase):
    """
    Attributes:
     - success

    """
    thrift_spec: typing.Any = None


    def __init__(self, success: typing.Optional[float] = None,):
        self.success: typing.Optional[float] = success

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(predictProba_result)
predictProba_result.thrift_spec = (
    (0, TType.DOUBLE, 'success', None, None, ),  # 0
)
fix_spec(all_structs)
del all_structs
