/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module tutorial.Calculator;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

import tutorial.tutorial_types;
import share.SharedService;

/**
  Ahh, now onto the cool part, defining a service. Services just need a name
and can optionally inherit from another service using the extends keyword.
*/
interface Calculator : SharedService {
  /**
    A method definition looks like C code. It has a return type, arguments,
and optionally a list of exceptions that it may throw. Note that argument
lists and exception lists are specified using the exact same syntax as
field lists in struct or exception definitions.
  */
  void ping();
  int add(int num1, int num2);
  int calculate(int logid, ref const(Work) w);
  /**
    This method has a oneway modifier. That means the client only makes
a request and does not listen for any response at all. Oneway methods
must be void.
  */
  void zip();

  alias tutorial.tutorial_types.InvalidOperation InvalidOperation;

  enum methodMeta = [
    TMethodMeta(`add`, 
      [TParamMeta(`num1`, 1), TParamMeta(`num2`, 2)]
    ),
    TMethodMeta(`calculate`, 
      [TParamMeta(`logid`, 1), TParamMeta(`w`, 2)],
      [TExceptionMeta(`ouch`, 1, `InvalidOperation`)]
    ),
    TMethodMeta(`zip`, 
      [],
      [],
      TMethodType.ONEWAY
    )
  ];
}
