/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module tutorial.tutorial_types;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

public import share.shared_types;

/**
  You can define enums, which are just 32 bit integers. Values are optional
and start at 1 if not supplied, C style again.
*/
enum Operation {
  ADD = 1,  SUBTRACT = 2,  MULTIPLY = 3,  DIVIDE = 4,
}

/**
  Thrift lets you do typedefs to get pretty names for your types. Standard
C style here.
*/
alias int MyInteger;

struct Work {
  int num1;
  int num2;
  Operation op;
  string comment;
  
  mixin TStructHelpers!([
    TFieldMeta(`num1`, 1, TReq.OPT_IN_REQ_OUT, q{0}),
    TFieldMeta(`num2`, 2, TReq.OPT_IN_REQ_OUT),
    TFieldMeta(`op`, 3, TReq.OPT_IN_REQ_OUT),
    TFieldMeta(`comment`, 4, TReq.OPTIONAL)
  ]);
}

class InvalidOperation : TException {
  int whatOp;
  string why;
  
  mixin TStructHelpers!([
    TFieldMeta(`whatOp`, 1, TReq.OPT_IN_REQ_OUT),
    TFieldMeta(`why`, 2, TReq.OPT_IN_REQ_OUT)
  ]);
}

