/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module tutorial.tutorial_constants;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

import tutorial.tutorial_types;

/**
  Thrift also lets you define constants for use across languages. Complex
types and structs are specified using JSON notation.
*/
immutable(int) INT32CONSTANT;
immutable(string[string]) MAPCONSTANT;

shared static this() {
  INT32CONSTANT = 9853;

  MAPCONSTANT = cast(immutable(string[string])) {
    string[string] v;
    v["goodnight"] = "moon";
    v["hello"] = "world";
    return v;
  }();
}
