/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module classifier.classificator_types;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;
