/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
module classifier.ClassifierService;

import thrift.base;
import thrift.codegen.base;
import thrift.util.hashset;

import classifier.classificator_types;

interface ClassifierService
{
	/**
    One online-training update using sgd.
  */
	void trainOnExample(double[] features, int result);
	/**
    Predict probability for class=1
  */
	double predictProba(double[] features);

	static immutable methodMeta = [
		TMethodMeta(`trainOnExample`,
			[TParamMeta(`features`, 1), TParamMeta(`result`, 2)]
		),
		TMethodMeta(`predictProba`,
			[TParamMeta(`features`, 1)]
		)
	];
}
